# DO NOT EDIT.
# This file was autogenerated by Kataru based on your story.
const August = "August"
const June = "June"
const May = "May"
const Test3 = "Test3"

const NAMES: Array[String] = [
    August,
    June,
    May,
    Test3
]

# Returns the character property for usage in the editor.
static func property(property_name: String) -> Dictionary:
	return {
		"name": property_name,
		"type": TYPE_STRING,
		"usage": PROPERTY_USAGE_DEFAULT,
		"hint": PROPERTY_HINT_ENUM,
		"hint_string": ",".join(NAMES)
	}
