# DO NOT EDIT.
# This file was autogenerated by Kataru based on your story.
const August = "August"
const June = "June"
const May = "May"
const Test2 = "Test2"

const NAMES: Array[String] = [
    August,
    June,
    May,
    Test2
]

# Returns the property for usage in the editor.
static func property(property_name: String) -> Dictionary:
	return {
		"name": property_name,
		"type": TYPE_STRING,
		"usage": PROPERTY_USAGE_DEFAULT,
		"hint": PROPERTY_HINT_ENUM,
		"hint_string": "August,June,May,Test2"
	}
