# DO NOT EDIT.
# This file was autogenerated by Kataru based on your story.
const character_set_animator_trigger = "$character.set_animator_trigger"
const wait = "wait"

# Adapters.
var adapters: Dictionary = {
	character_set_animator_trigger: func(f: Callable, params: Dictionary): f.call(params.name),
	wait: func(f: Callable, params: Dictionary): f.call(params.duration)
}

var registry: Dictionary = {}


func call_command(cmd_name: String, normalized_name: String, params: String):
	self.adapters[normalized_name].call(self.registry[cmd_name], JSON.parse_string(params))

