# DO NOT EDIT.
# This file was autogenerated by Kataru based on your story.

# Adapters.
var adapters: Dictionary = {}

var registry: Dictionary = {}


func call_command(cmd_name: String, normalized_name: String, params: String):
	self.adapters[normalized_name].call(self.registry[cmd_name], JSON.parse_string(params))
