# DO NOT EDIT.
# This file was autogenerated by Kataru based on your story.
const End = "End"
const NoCoffee = "NoCoffee"
const Start = "Start"
const YesCoffee = "YesCoffee"

const NAMES: Array[String] = [
    End,
    NoCoffee,
    Start,
    YesCoffee
]

# Returns the property for usage in the editor.
static func property(property_name: String) -> Dictionary:
	return {
		"name": property_name,
		"type": TYPE_STRING,
		"usage": PROPERTY_USAGE_DEFAULT,
		"hint": PROPERTY_HINT_ENUM,
		"hint_string": "End,NoCoffee,Start,YesCoffee"
	}
